"""Seed content for Rosh Charcoal — editable later via admin/CMS."""

ARTWORKS = [
    {
        "slug": "the-quiet-hour",
        "title": "The Quiet Hour",
        "year": 2026,
        "medium": "Charcoal",
        "category": "Portraits",
        "tags": ["charcoal", "portrait", "female"],
        "surface": "Fabriano handmade paper, 300gsm",
        "dimensions": "42 × 59 cm (A2)",
        "framing": "Available framed in natural oak on request",
        "availability": "Available",
        "price": 42000,
        "price_visibility": "show",
        "featured": True,
        "order": 1,
        "main_image": "https://images.unsplash.com/photo-1748200099986-5ed2ca9ae4a6?crop=entropy&cs=srgb&fm=jpg&q=90&w=1600",
        "images": [
            "https://images.unsplash.com/photo-1748200099986-5ed2ca9ae4a6?crop=entropy&cs=srgb&fm=jpg&q=90&w=1600",
            "https://images.pexels.com/photos/7608653/pexels-photo-7608653.jpeg?auto=compress&cs=tinysrgb&w=1400"
        ],
        "alt": "Charcoal portrait of a woman looking to the side, soft shoulders",
        "statement": "She sat still for a long time, and the room went quiet around her. I wanted the charcoal to hold that stillness — the weight of a thought she never said aloud.",
    },
    {
        "slug": "father-in-grey",
        "title": "Father, in Grey",
        "year": 2025,
        "medium": "Charcoal",
        "category": "Portraits",
        "tags": ["charcoal", "portrait", "male"],
        "surface": "Cotton rag paper, 250gsm",
        "dimensions": "50 × 70 cm",
        "framing": "Unframed",
        "availability": "Sold",
        "price": 55000,
        "price_visibility": "show",
        "featured": True,
        "order": 2,
        "main_image": "https://images.unsplash.com/photo-1761726114786-eba9854b440d?crop=entropy&cs=srgb&fm=jpg&q=90&w=1600",
        "images": ["https://images.unsplash.com/photo-1761726114786-eba9854b440d?crop=entropy&cs=srgb&fm=jpg&q=90&w=1600"],
        "alt": "Charcoal portrait of a man in a suit, formal and composed",
        "statement": "A commission for a daughter who wanted to remember her father the way he stood — upright, certain, quietly proud.",
    },
    {
        "slug": "study-no-7",
        "title": "Study No. 7",
        "year": 2026,
        "medium": "Graphite",
        "category": "Studies",
        "tags": ["graphite", "study", "eyes"],
        "surface": "Smooth Bristol board",
        "dimensions": "21 × 29 cm (A4)",
        "framing": "Unframed",
        "availability": "Available",
        "price": 14000,
        "price_visibility": "show",
        "featured": True,
        "order": 3,
        "main_image": "https://images.pexels.com/photos/7608653/pexels-photo-7608653.jpeg?auto=compress&cs=tinysrgb&w=1400",
        "images": ["https://images.pexels.com/photos/7608653/pexels-photo-7608653.jpeg?auto=compress&cs=tinysrgb&w=1400"],
        "alt": "Detailed graphite study of human eyes",
        "statement": "The eyes carry everything. This was an early morning study — just the eyes, again and again, until they looked back.",
    },
    {
        "slug": "unspoken",
        "title": "Unspoken",
        "year": 2025,
        "medium": "Charcoal",
        "category": "Figures",
        "tags": ["charcoal", "figure"],
        "surface": "Toned tan paper",
        "dimensions": "40 × 50 cm",
        "framing": "Available framed",
        "availability": "Private Collection",
        "price": None,
        "price_visibility": "request",
        "featured": True,
        "order": 4,
        "main_image": "https://images.unsplash.com/photo-1771257824559-0a4fc650d6cd?crop=entropy&cs=srgb&fm=jpg&q=90&w=1600",
        "images": ["https://images.unsplash.com/photo-1771257824559-0a4fc650d6cd?crop=entropy&cs=srgb&fm=jpg&q=90&w=1600"],
        "alt": "Charcoal portrait of a man's face, expressive and tonal",
        "statement": "Some faces resist being drawn. This one kept slipping away until I stopped trying to capture a likeness and started listening to the silence in it.",
    },
    {
        "slug": "her-yellow-glance",
        "title": "Her Yellow Glance",
        "year": 2026,
        "medium": "Graphite",
        "category": "Portraits",
        "tags": ["graphite", "portrait", "female"],
        "surface": "Hot-pressed watercolour paper",
        "dimensions": "30 × 40 cm",
        "framing": "Unframed",
        "availability": "Available",
        "price": 28000,
        "price_visibility": "show",
        "featured": True,
        "order": 5,
        "main_image": "https://images.unsplash.com/photo-1612641605722-60c66c66530c?crop=entropy&cs=srgb&fm=jpg&q=90&w=1600",
        "images": ["https://images.unsplash.com/photo-1612641605722-60c66c66530c?crop=entropy&cs=srgb&fm=jpg&q=90&w=1600"],
        "alt": "Graphite sketch of a woman with a single coloured eye",
        "statement": "A single touch of colour in an otherwise grey world — the one detail she asked me never to leave out.",
    },
    {
        "slug": "morning-face",
        "title": "Morning Face",
        "year": 2024,
        "medium": "Charcoal",
        "category": "Portraits",
        "tags": ["charcoal", "portrait", "female"],
        "surface": "Ivory drawing paper",
        "dimensions": "35 × 50 cm",
        "framing": "Unframed",
        "availability": "Commissioned",
        "price": None,
        "price_visibility": "request",
        "featured": True,
        "order": 6,
        "main_image": "https://images.unsplash.com/photo-1593472807861-5bb884af28f6?crop=entropy&cs=srgb&fm=jpg&q=90&w=1600",
        "images": ["https://images.unsplash.com/photo-1593472807861-5bb884af28f6?crop=entropy&cs=srgb&fm=jpg&q=90&w=1600"],
        "alt": "Charcoal sketch of a woman's face on paper",
        "statement": "Drawn from a photograph taken on an ordinary morning. The client wanted the version of herself no one usually sees.",
    },
    {
        "slug": "hands-that-remember",
        "title": "Hands That Remember",
        "year": 2025,
        "medium": "Graphite",
        "category": "Studies",
        "tags": ["graphite", "study"],
        "surface": "Smooth cartridge paper",
        "dimensions": "25 × 25 cm",
        "framing": "Unframed",
        "availability": "Available",
        "price": 16000,
        "price_visibility": "show",
        "featured": False,
        "order": 7,
        "main_image": "https://images.pexels.com/photos/7608654/pexels-photo-7608654.jpeg?auto=compress&cs=tinysrgb&w=1400",
        "images": ["https://images.pexels.com/photos/7608654/pexels-photo-7608654.jpeg?auto=compress&cs=tinysrgb&w=1400"],
        "alt": "Graphite study of facial features and nose",
        "statement": "A study of the small features we forget we love until they are gone.",
    },
    {
        "slug": "the-drawing-hand",
        "title": "The Drawing Hand",
        "year": 2024,
        "medium": "Charcoal",
        "category": "Figures",
        "tags": ["charcoal", "process"],
        "surface": "Newsprint study",
        "dimensions": "29 × 42 cm (A3)",
        "framing": "Not for sale",
        "availability": "Not for Sale",
        "price": None,
        "price_visibility": "hide",
        "featured": False,
        "order": 8,
        "main_image": "https://images.unsplash.com/photo-1674643925879-d457c6e93801?crop=entropy&cs=srgb&fm=jpg&q=90&w=1600",
        "images": ["https://images.unsplash.com/photo-1674643925879-d457c6e93801?crop=entropy&cs=srgb&fm=jpg&q=90&w=1600"],
        "alt": "A person drawing a portrait on paper",
        "statement": "A study of the act itself — the hand, the paper, the moment before a face appears.",
    },
]

PRICING = [
    {"name": "Mini Portrait", "size": "A5 · 15 × 21 cm", "subjects": "1 subject", "medium": "Graphite or charcoal", "timeline": "1–2 weeks", "framing": "Unframed", "price_from": 9000, "order": 1},
    {"name": "Standard Portrait", "size": "A4 · 21 × 29 cm", "subjects": "1 subject", "medium": "Charcoal", "timeline": "2–3 weeks", "framing": "Framing optional", "price_from": 18000, "order": 2},
    {"name": "Detailed Portrait", "size": "A3 · 30 × 42 cm", "subjects": "1 subject", "medium": "Charcoal, fine detail", "timeline": "3–4 weeks", "framing": "Framing optional", "price_from": 32000, "order": 3},
    {"name": "Large Portrait", "size": "50 × 70 cm", "subjects": "1 subject", "medium": "Charcoal", "timeline": "4–6 weeks", "framing": "Framing recommended", "price_from": 55000, "order": 4},
    {"name": "Two-Person Portrait", "size": "A3–50 × 70 cm", "subjects": "2 subjects", "medium": "Charcoal", "timeline": "5–7 weeks", "framing": "Framing optional", "price_from": 68000, "order": 5},
    {"name": "Custom Size", "size": "By discussion", "subjects": "Multiple subjects", "medium": "Charcoal or graphite", "timeline": "Quoted per project", "framing": "By discussion", "price_from": None, "order": 6},
]

TESTIMONIALS = [
    {"name": "Ananya", "city": "Bengaluru", "type": "Memorial portrait", "quote": "I cried when I opened the parcel. It was my grandmother exactly as I remembered her — not a photograph, something warmer.", "image": "https://images.unsplash.com/photo-1593472807861-5bb884af28f6?crop=entropy&cs=srgb&fm=jpg&q=85&w=600", "order": 1},
    {"name": "Rahul", "city": "London", "type": "Anniversary gift", "quote": "Rosh understood what I couldn't put into words. The portrait of my wife now hangs where we see it every morning.", "image": "", "order": 2},
    {"name": "Meera", "city": "Dubai", "type": "Wedding commission", "quote": "Patient, thoughtful, and quietly brilliant. The detail in the charcoal is unbelievable in person.", "image": "https://images.unsplash.com/photo-1612641605722-60c66c66530c?crop=entropy&cs=srgb&fm=jpg&q=85&w=600", "order": 3},
]

JOURNAL = [
    {
        "slug": "the-story-behind-the-quiet-hour",
        "title": "The Story Behind 'The Quiet Hour'",
        "category": "Behind the Artwork",
        "excerpt": "Every portrait begins with a moment of stillness. Here is the one that started this piece.",
        "author": "Rosh",
        "reading_time": 4,
        "cover": "https://images.unsplash.com/photo-1748200099986-5ed2ca9ae4a6?crop=entropy&cs=srgb&fm=jpg&q=90&w=1600",
        "date": "2026-04-18",
        "related_artwork": "the-quiet-hour",
        "body": "There is a particular kind of quiet that settles over a room when someone finally stops performing for the camera.\n\nI had been photographing my subject for almost an hour, and nothing felt right. Then she looked away — not for the drawing, just for herself — and everything changed. The light fell across her cheek. Her shoulders softened.\n\nCharcoal is the only medium that can hold that softness for me. It smudges, it forgives, it remembers the pressure of the hand. I built her face in layers over four days, letting the paper grain do half the work.\n\nWhen people ask why I don't work in colour, this is the answer. Grey is where feeling lives.",
    },
    {
        "slug": "how-to-choose-a-reference-photograph",
        "title": "How to Choose a Reference Photograph",
        "category": "Commission Stories",
        "excerpt": "The single most important decision you'll make when commissioning a portrait.",
        "author": "Rosh",
        "reading_time": 5,
        "cover": "https://images.pexels.com/photos/35376331/pexels-photo-35376331.jpeg?auto=compress&cs=tinysrgb&w=1600",
        "date": "2026-03-30",
        "related_artwork": "her-yellow-glance",
        "body": "A charcoal portrait is only ever as honest as the photograph it begins with.\n\nI'm often sent lovely, heavily-filtered phone photos — and I always ask for something plainer. Here is what actually helps: soft, natural light from a window; a face that isn't blurred or over-smoothed; and an expression that feels like the person, not a pose.\n\nIf the photograph is a little imperfect but full of character, that is far more useful to me than a flawless studio shot. I can draw a wrinkle. I cannot draw a filter.\n\nWhen in doubt, send me three or four images. I'll tell you which one holds the story.",
    },
    {
        "slug": "how-to-protect-a-charcoal-drawing",
        "title": "How to Protect a Charcoal Drawing",
        "category": "Portrait Care",
        "excerpt": "Charcoal is delicate by nature. A few simple habits will keep your portrait pristine for decades.",
        "author": "Rosh",
        "reading_time": 3,
        "cover": "https://images.unsplash.com/photo-1589637458063-7b054f0c18ab?crop=entropy&cs=srgb&fm=jpg&q=90&w=1600",
        "date": "2026-03-10",
        "related_artwork": "study-no-7",
        "body": "Charcoal sits on the surface of the paper rather than soaking into it, which is exactly what gives it that velvety depth — and also what makes it fragile.\n\nEvery portrait I send is sealed with a light archival fixative, but the real protection is framing behind glass, away from direct sunlight and humidity. Never wipe the surface. Never store it flat under weight.\n\nTreated with a little care, a charcoal drawing will outlive all of us — the pigment is essentially pure carbon, one of the most stable materials there is.",
    },
]

PRINT_EDITIONS = [
    {"id": "study-a5", "title": "Study Print — A5", "size": "15 × 21 cm", "edition": "Open edition", "paper": "310gsm cotton rag, giclée", "price": 1800, "image": "https://images.pexels.com/photos/7608653/pexels-photo-7608653.jpeg?auto=compress&cs=tinysrgb&w=1000", "order": 1, "active": True},
    {"id": "portrait-a4", "title": "Portrait Print — A4", "size": "21 × 29 cm", "edition": "Limited to 50", "paper": "310gsm cotton rag, giclée", "price": 3200, "image": "https://images.unsplash.com/photo-1593472807861-5bb884af28f6?crop=entropy&cs=srgb&fm=jpg&q=85&w=1000", "order": 2, "active": True},
    {"id": "statement-a3", "title": "Statement Print — A3", "size": "30 × 42 cm", "edition": "Limited to 25", "paper": "Hahnemühle museum etching", "price": 5400, "image": "https://images.unsplash.com/photo-1612641605722-60c66c66530c?crop=entropy&cs=srgb&fm=jpg&q=85&w=1000", "order": 3, "active": True},
    {"id": "collector-a2", "title": "Collector Print — A2", "size": "42 × 59 cm", "edition": "Limited to 15, signed", "paper": "Hahnemühle museum etching", "price": 8900, "image": "https://images.unsplash.com/photo-1748200099986-5ed2ca9ae4a6?crop=entropy&cs=srgb&fm=jpg&q=85&w=1000", "order": 4, "active": True},
]

SETTINGS = {
    "commission_status": "Commissions Open",
    "response_time": "I usually respond to enquiries within 2–3 working days.",
    "journal_enabled": True,
    "instagram": "https://www.instagram.com/roshcharcoal?igsh=MTVoNzlzMGhoa3dpeQ==",
    "whatsapp": "+91 9035615236",
    "email": "roshcharcoal@gmail.com",
}
